import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {getSql,activeSession,signActor} from '../packages/db/src/index.ts';
const R='/Users/macbook/Documents/Codex/portfolio',base='http://127.0.0.1:8979',gateway='http://127.0.0.1:8978';
const checks:string[]=[];let stage='health',requests=0;
class Client{cookies=new Map<string,string>();owner='';email=`http-${randomUUID()}@example.invalid`;password=randomBytes(25).toString('base64url');
 async request(path:string,method='GET',body?:unknown,extra:Record<string,string>={}){requests++;const headers:Record<string,string>={cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; '),...extra};if(method!=='GET')headers.Origin=base;let raw:string|undefined;if(body!==undefined){raw=typeof body==='string'?body:JSON.stringify(body);headers['content-type']??='application/json';}
 const r=await fetch(base+path,{method,headers,body:raw,redirect:'manual',signal:AbortSignal.timeout(120000)});for(const c of r.headers.getSetCookie()){const pair=c.split(';')[0]!;const i=pair.indexOf('=');this.cookies.set(pair.slice(0,i),pair.slice(i+1));}const text=await r.text();let data:any;try{data=JSON.parse(text);}catch{data=null;}return{status:r.status,data,text,headers:r.headers};}
 async signin(password=this.password){const csrf=await this.request('/api/auth/csrf');return this.request('/api/auth/callback/credentials','POST',new URLSearchParams({csrfToken:csrf.data.csrfToken,email:this.email,password,callbackUrl:base}).toString(),{'content-type':'application/x-www-form-urlencoded','x-auth-return-redirect':'1'});}
 async signout(){const csrf=await this.request('/api/auth/csrf');return this.request('/api/auth/signout','POST',new URLSearchParams({csrfToken:csrf.data.csrfToken,callbackUrl:base}).toString(),{'content-type':'application/x-www-form-urlencoded','x-auth-return-redirect':'1'});}
}
const manifest=JSON.parse(readFileSync('apps/dashboard/.next-integrated/server/server-reference-manifest.json','utf8'));
async function action(c:Client,name:string,args:unknown[],path='/settings'){
 const id=Object.entries(manifest.node).find(([,v]:[string,any])=>v.exportedName===name)?.[0];assert(id,`action ${name}`);
 const r=await c.request(path,'POST',args,{'next-action':id!,accept:'text/x-component'});const line=r.text.split('\n').find(x=>x.startsWith('1:'));const result=line?JSON.parse(line.slice(2)):null;return{...r,result};
}
async function actor(c:Client){const row=(await getSql()`SELECT s.id,u.id AS owner FROM blindspot.sessions s JOIN blindspot.users u ON u.id=s.owner_id WHERE u.email=${c.email} AND s.revoked_at IS NULL ORDER BY s.created_at DESC LIMIT 1`)[0]!;return (await activeSession(row.owner,row.id))!;}
async function manage(c:Client,path:string,method='GET',body?:unknown){const raw=body===undefined?'':JSON.stringify(body);requests++;const r=await fetch(gateway+path,{method,headers:{'x-blindspot-actor':signActor(await actor(c),method,path,raw),'content-type':'application/json'},body:method==='GET'?undefined:raw,signal:AbortSignal.timeout(120000)});return{status:r.status,data:await r.json() as any};}
async function sdk(key:string,path:string,method='POST',body?:unknown){requests++;const r=await fetch(gateway+path,{method,headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:method==='GET'?undefined:JSON.stringify(body??{}),redirect:'manual',signal:AbortSignal.timeout(15000)});return{status:r.status,data:await r.json() as any};}
try{
 assert(process.env.DATABASE_URL?.includes('/blindspot_auth_test'));const a=new Client(),b=new Client();const health=await a.request('/api/healthz');assert.equal(health.status,200);assert.equal(health.data.mock,true);checks.push('compiled_health_auth_mock');
 stage='signup';const fresh1=new Client(),fresh2=new Client();const [one,two]=await Promise.all([fresh1.request('/api/session'),fresh2.request('/api/session')]);a.cookies=fresh2.cookies;const mixed=await a.request('/api/signup','POST',{email:a.email,password:a.password,csrf:one.data.csrf});assert.equal(mixed.status,201);checks.push('mixed_initial_session_responses_signup_succeeds');
 const bad=await b.request('/api/signup','POST',{email:b.email,password:b.password,csrf:'forged'});assert.equal(bad.status,403);checks.push('forged_csrf_denied');
 const bs=await b.request('/api/session');const created=await b.request('/api/signup','POST',{email:b.email,password:b.password,csrf:bs.data.csrf});assert.equal(created.status,201);
 stage='signin';const wrong=await a.signin('incorrect-password-123');assert.equal(typeof wrong.data.url,'string');assert(new URL(wrong.data.url,base).searchParams.has('error'));checks.push('actual_authjs_bad_password_contract');
 for(const c of[a,b]){const r=await c.signin();assert.equal(r.status,200);assert(!new URL(r.data.url,base).searchParams.has('error'));const s=await c.request('/api/session');assert(s.data.user?.id);c.owner=s.data.user.id;}
 checks.push('actual_authjs_two_owner_signin');
 const [s1,s2]=await Promise.all([a.request('/api/session'),a.request('/api/session')]);assert.equal(s1.data.csrf,s2.data.csrf);checks.push('same_session_csrf_reusable');
 const denied=await b.request('/api/signup','POST',{email:'unused-'+randomUUID()+'@example.invalid',password:b.password,csrf:s1.data.csrf});assert.equal(denied.status,403);checks.push('foreign_authenticated_csrf_denied');
 requests++;const wrongOrigin=await fetch(base+'/api/signup',{method:'POST',headers:{Origin:'https://foreign.example','content-type':'application/json'},body:JSON.stringify({email:a.email,password:a.password,csrf:s1.data.csrf})});assert.notEqual(wrongOrigin.status,201);checks.push('wrong_origin_denied');
 stage='actions';const changed=await action(b,'mintKeyA',[a.owner]);assert.equal(changed.result?.code,'SESSION_CHANGED');checks.push('delayed_owner_a_action_under_b_cookie_denied');
 const countBefore=Number((await getSql()`SELECT count(*)::int AS n FROM blindspot.usage`)[0]!.n);
 stage='example';const ownProject=(await actor(a)).projectId;
 const collisionWf=(await getSql()`INSERT INTO blindspot.workflows(project_id,name,environment) VALUES(${ownProject},'Prepared support triage','prepared') RETURNING id`)[0]!;
 const collisionRoute=(await getSql()`INSERT INTO blindspot.routes(project_id,name,live_model,policy_json) VALUES(${ownProject},'Prepared support triage@prepared:classify-request','openai:gpt-4o','{}'::jsonb) RETURNING id`)[0]!;
 const ex=await action(a,'createExampleA',[a.owner],'/');assert.equal(ex.result?.ok,true,JSON.stringify(ex.result));const example=ex.result;assert(example.prepared);checks.push('compiled_server_action_genuine_sdk_prepared_example');
 const ex2=await action(a,'createExampleA',[a.owner],'/');assert.equal(ex2.result?.workflowId,example.workflowId);checks.push('example_idempotent');
 assert.equal((await getSql()`SELECT example_kind FROM blindspot.workflows WHERE id=${collisionWf.id}`)[0]!.example_kind,null);const oldRoute=(await getSql()`SELECT live_model,example_kind FROM blindspot.routes WHERE id=${collisionRoute.id}`)[0]!;assert.equal(oldRoute.live_model,'openai:gpt-4o');assert.equal(oldRoute.example_kind,null);checks.push('ordinary_name_collisions_preserved');
 const details=await manage(a,'/v1/workflows/'+example.workflowId);assert.equal(details.status,200);assert.equal((await manage(b,'/v1/workflows/'+example.workflowId)).status,404);checks.push('foreign_workflow_denied');
 const wf=(await getSql()`SELECT example_kind,name FROM blindspot.workflows WHERE id=${example.workflowId}`)[0]!;assert.equal(wf.example_kind,'prepared');
 const nodes=await getSql()`SELECT n.id,r.id AS route_id FROM blindspot.workflow_nodes n JOIN blindspot.routes r ON r.id=n.route_id WHERE n.workflow_id=${example.workflowId}`;assert.equal(nodes.length,1);
 const runs=await getSql()`SELECT status,actual_cost_cents FROM blindspot.eval_runs WHERE route_id=${nodes[0]!.route_id}`;assert(runs.length>=2);assert(runs.every(x=>x.status==='completed'&&Number(x.actual_cost_cents)===0));
 assert.equal(Number((await getSql()`SELECT count(*)::int AS n FROM blindspot.usage`)[0]!.n),countBefore);checks.push('prepared_observed_node_evals_zero_usage');
 const temp=await getSql()`SELECT revoked_at FROM blindspot.api_keys WHERE project_id=${(await actor(a)).projectId} AND expires_at IS NOT NULL`;assert(temp.length&&temp.every(x=>x.revoked_at));checks.push('temporary_sdk_telemetry_key_revoked');
 const ge=(await getSql()`SELECT e.id FROM blindspot.golden_examples e JOIN blindspot.golden_sets g ON g.id=e.golden_set_id WHERE g.route_id=${nodes[0]!.route_id} LIMIT 1`)[0]!;
 assert.equal((await manage(a,'/v1/golden-examples/'+String(ge.id).toUpperCase(),'DELETE')).status,409);assert.equal((await manage(a,'/v1/workflows/'+String(example.workflowId).toUpperCase(),'PATCH',{name:'changed'})).status,409);checks.push('uppercase_prepared_ids_remain_immutable');
 assert.equal((await manage(b,'/v1/routes/'+encodeURIComponent(example.routeName))).status,404);assert.equal((await manage(b,'/v1/golden-examples/'+ge.id,'DELETE')).status,404);const ep=(await getSql()`SELECT id FROM blindspot.eval_plans WHERE route_id=${nodes[0]!.route_id} LIMIT 1`)[0]!;assert.equal((await manage(b,'/v1/eval-plans/'+ep.id)).status,404);checks.push('foreign_route_golden_and_eval_plan_denied');
 assert.equal((await manage(a,'/v1/feedback','POST',{workflow:{name:wf.name,environment:'prepared'},executionId:'prepared-'+example.workflowId,kind:'up'})).status,409);checks.push('prepared_feedback_denied');
 stage='catalog';const synced=await manage(a,'/v1/model-registry/sync','POST',{provider:'openai'});assert.equal(synced.status,200);const catalog=await manage(a,'/v1/model-registry');assert.equal(catalog.status,200);assert(JSON.stringify(catalog.data).includes('openai:gpt-4o-mini'));checks.push('configured_openai_catalog_available');
 stage='keys';const key=(await manage(a,'/v1/keys','POST',{})).data.key;assert(key.key);assert.equal((await sdk(key.key,'/v1/keys','GET')).status,403);assert.equal((await sdk(key.key,'/v1/keys','POST')).status,403);assert.equal((await sdk(key.key,'/v1/chat/completions/','POST')).status,403);checks.push('sdk_exact_method_path_management_denial');
 const chat=await sdk(key.key,'/v1/chat/completions','POST',{model:'openai:gpt-4o-mini',messages:[{role:'user',content:'Bearer sk-test-sensitive-secret-1234567890'}],max_tokens:64});assert.equal(chat.status,200);checks.push('normal_mock_sdk_completion');
 const tr=(await getSql()`SELECT project_id,route_id,input,output FROM blindspot.traces WHERE project_id=${(await actor(a)).projectId} ORDER BY created_at DESC LIMIT 1`)[0]!;assert(tr.project_id);assert.equal(tr.route_id,null);assert.equal(tr.input.unavailable,true);assert.equal(tr.output,null);checks.push('direct_model_trace_owner_metadata_capture');
 assert.equal((await manage(b,'/v1/keys/'+key.id,'DELETE')).status,404);checks.push('foreign_sdk_key_cannot_be_revoked');
 assert.equal((await manage(a,'/v1/data-controls','PATCH',{captureMode:'full'})).status,200);const marker=randomBytes(24).toString('hex');assert.equal((await sdk(key.key,'/v1/chat/completions','POST',{model:'openai:gpt-4o-mini',messages:[{role:'user',content:'Bearer '+marker}],max_tokens:64})).status,200);const full=(await getSql()`SELECT input FROM blindspot.traces WHERE project_id=${(await actor(a)).projectId} ORDER BY created_at DESC LIMIT 1`)[0]!;assert(!JSON.stringify(full.input).includes(marker));assert(JSON.stringify(full.input).includes('[REDACTED]'));checks.push('full_capture_redacts_credentials');
 assert.equal((await manage(a,'/v1/data-controls','PATCH',{captureMode:'metadata'})).status,200);
 assert.equal((await manage(a,'/v1/keys/'+key.id,'DELETE')).status,200);assert.equal((await sdk(key.key,'/v1/chat/completions','POST',{model:'openai:gpt-4o-mini',messages:[{role:'user',content:'hi'}]})).status,401);checks.push('last_sdk_key_revocation_preserves_human');
 stage='revoke';const stolen=new Client();stolen.cookies=new Map(a.cookies);assert.equal((await a.signout()).status,200);assert.equal((await stolen.request('/api/session')).data.user,null);checks.push('copied_cookie_durably_revoked');
 writeFileSync(R+'/_private/blindspot-http-test-accounts.json',JSON.stringify({base,accounts:{A:{email:a.email,password:a.password,ownerId:a.owner},B:{email:b.email,password:b.password,ownerId:b.owner}},example}),{mode:0o600});
 const receipt={status:'passed',checks,requests,actualPostgres:true,actualCompiledAuthJS:true,actualCompiledServerActions:true,providerCalls:0};writeFileSync(R+'/_verify/blindspot/auth-http.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({status:'passed',checks:checks.length,requests,providerCalls:0}));
}catch(e){const err=e as Error;writeFileSync(R+'/_verify/blindspot/auth-http-failure.json',JSON.stringify({status:'failed',stage,checks,requests,error:err.name,message:err.message.slice(0,2000)},null,2));console.log(JSON.stringify({status:'failed',stage,error:err.name,message:err.message.slice(0,1500)}));process.exitCode=1;}finally{await getSql().end({timeout:5});}
